# permissions for end users to view emqxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: emqx-operator
    app.kubernetes.io/managed-by: kustomize
  name: emqx-viewer-role
rules:
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxes/status
  verbs:
  - get
